C:\Windows\System32\regsvr32 /s "C:\Profut\Compilado\Lib\CadastroDeJogador.dll"
C:\Windows\System32\regsvr32 /s "C:\Profut\Compilado\Lib\CadEquipe.dll"
C:\Windows\System32\regsvr32 /s "C:\Profut\Compilado\Lib\modExcell.dll"
C:\Windows\System32\regsvr32 /s "C:\Profut\Compilado\Lib\RelJogador.dll"
C:\Windows\System32\regsvr32 /s "C:\Profut\Compilado\Lib\SMConexao.dll"