USE dbFUTEBOL
CREATE TABLE dbo.EQUIPE_T(
	ID_IN int IDENTITY(1,1) NOT NULL,
	NOME_VC varchar(128) NOT NULL,
	SIGLA_VC varchar(128) NOT NULL,
	RESPONSAVEL_VC varchar(128) NULL,
	CONTATO1_VC varchar(128) NULL,
	WHATSAPP1_BT bit NULL,
	CONTATO2_VC varchar(128) NULL,
	WHATSAP2_BT bit NULL,
	EMAILCONTATO_VC varchar(128) NULL,
	ENDERECOIMAGEM_VC varbinary(max) NULL,
	EXCLUIDO_BT bit NULL,
	USUARIOCADASTRO_VC varchar(128) NULL,
	USUARIOULTIMAALTERACAO_VC varchar(128) NULL,
	DATACADASTRO_DT datetime NULL,
	DATAULTIMAALTERACAO_DT datetime NULL
)
