IF ( SELECT COUNT(*)
     FROM   SYSOBJECTS
     WHERE  xtype = 'P'
            AND name = 'USP_ADICIONARCAMPEONATO'
   ) > 0 
    BEGIN
        DROP PROCEDURE USP_ADICIONARCAMPEONATO
    END

GO

CREATE PROCEDURE USP_ADICIONARCAMPEONATO
    (
		@NOME_VC VARCHAR(128) NOT NULL,
		@DESCRICAO_VC VARCHAR(128) = NULL,
		@EDICAO_IN INT NOT NULL,
		@CARTEGORIA_IN INT NOT NULL,
		@FACEBOOK_VC VARCHAR(128) = NULL,
		@INSTAGRAM_VC VARCHAR(128) = NULL,
		@DATAINICIO_DT DATETIME NOT NULL,
		@DATAFINAL_DT DATETIME  = NULL,
		@ATIVO_BT BIT NOT NULL,
		@USUARIOCADASTRO_VC VARCHAR(128) = NULL,
		@USUARIOULTIMAALTERACAO_VC VARCHAR(128) = NULL,
		@DATACADASTRO_DT DATETIME NOT NULL,
		@DATAULTIMAALTERACAO_DT DATETIME NOT NULL
    )
AS 
    INSERT INTO dbo.CAMPEONATO_T
            ( NOME_VC ,
              DESCRICAO_VC ,
              EDICAO_IN ,
              CARTEGORIA_IN ,
              FACEBOOK_VC ,
              INSTAGRAM_VC ,
              DATAINICIO_DT ,
              DATAFINAL_DT ,
              ATIVO_BT ,
              USUARIOCADASTRO_VC ,
              USUARIOULTIMAALTERACAO_VC ,
              DATACADASTRO_DT ,
              DATAULTIMAALTERACAO_DT
            )
    VALUES  (	
			@NOME_VC ,
			@DESCRICAO_VC ,
			@EDICAO_IN ,
			@CARTEGORIA_IN ,
			@FACEBOOK_VC ,
			@INSTAGRAM_VC ,
			@DATAINICIO_DT ,
			@DATAFINAL_DT ,
			@ATIVO_BT ,
			@USUARIOCADASTRO_VC ,
			@USUARIOULTIMAALTERACAO_VC ,
			@DATACADASTRO_DT ,
			@DATAULTIMAALTERACAO_DT 
            )
            
    RETURN SCOPE_IDENTITY()
	        
GO 

GRANT EXECUTE ON USP_ADICIONARCAMPEONATO TO PUBLIC

GO

IF ( SELECT COUNT(*)
     FROM   SYSOBJECTS
     WHERE  xtype = 'P'
            AND name = 'USP_ALTERARCAMPEONATO'
   ) > 0 
    BEGIN
        DROP PROCEDURE USP_ALTERARCAMPEONATO
    END

GO

CREATE PROCEDURE USP_ALTERARCAMPEONATO
    (
      @CAMPEONATO_IN INT ,
      @NOME_VC VARCHAR(128) ,
      @DESCRICAO_VC VARCHAR(128) = NULL ,
      @PARTICIPANTES_IN INT ,
      @DATAINICIO_DT DATETIME = NULL ,
      @DATAFINAL_DT DATETIME = NULL ,
      @CODIGO_IN INT OUTPUT
    )
AS 
    UPDATE  dbo.CAMPEONATO_T
    SET     NOME_VC = @NOME_VC ,
            DESCRICAO_VC = @DESCRICAO_VC ,
            PARTICIPANTES_IN = @PARTICIPANTES_IN ,
            DATAINICIO_DT = @DATAINICIO_DT ,
            DATAFINAL_DT = @DATAFINAL_DT
    WHERE   ID_IN = @CAMPEONATO_IN
            
    RETURN SCOPE_IDENTITY()

GO

GRANT EXECUTE ON USP_ALTERARCAMPEONATO TO PUBLIC

GO

IF ( SELECT COUNT(*)
     FROM   SYSOBJECTS
     WHERE  xtype = 'P'
            AND name = 'USP_APAGARCAMPEONATO'
   ) > 0 
    BEGIN
        DROP PROCEDURE USP_APAGARCAMPEONATO
    END

GO


CREATE PROCEDURE USP_APAGARCAMPEONATO ( @CAMPEONATO_IN INT )
AS 
    UPDATE  dbo.CAMPEONATO_T
    SET     EXCLUIDO_BT = 1
    WHERE   ID_IN = @CAMPEONATO_IN
    UPDATE  dbo.CAMPEONATOXEQUIPE_T
    SET     EXCLUIDO_BT = 1
    WHERE   CAMPEONATO_IN = @CAMPEONATO_IN

GO

GRANT EXECUTE ON USP_APAGARCAMPEONATO TO PUBLIC

GO

IF ( SELECT COUNT(*)
     FROM   SYSOBJECTS
     WHERE  xtype = 'P'
            AND name = 'USP_SELECIONARCAMPEONATOPORCODIGO'
   ) > 0 
    BEGIN
        DROP PROCEDURE USP_SELECIONARCAMPEONATOPORCODIGO
    END

GO

CREATE PROCEDURE USP_SELECIONARCAMPEONATOPORCODIGO ( @CAMPEONATO_IN INT )
AS 
    SET NOCOUNT ON
--TRAGO AS INFORMAÇÕES DO CAMPEONATO
    SELECT  CAM.ID_IN,
			CAM.NOME_VC ,
            CAM.DESCRICAO_VC ,
            CAM.DATAINICIO_DT ,
            CAM.DATAFINAL_DT ,
            CAM.PARTICIPANTES_IN,
            CAM.EXCLUIDO_BT
    FROM    dbo.CAMPEONATO_T CAM
    WHERE   CAM.ID_IN = @CAMPEONATO_IN
			--DECIDI TAMBÉM TRAZER OS EXCLUIDOS PARA DEIXAR "FLEGADO" NA INTERFACE

--TRAGO AS EQUIPES PARTICIPANTES
    SELECT  EQU.ID_IN,
			EQU.NOME_VC ,
            EQU.SIGLA_VC ,
            EQU.RESPONSAVEL_VC ,
            EQU.CONTATO_VC,
            EQU.EXCLUIDO_BT,
            CXE.EXCLUIDO_BT
            
    FROM	dbo.EQUIPE_T EQU
			INNER JOIN dbo.CAMPEONATOXEQUIPE_T CXE ON EQU.ID_IN = CXE.EQUIPE_IN
    
    WHERE   CXE.CAMPEONATO_IN = @CAMPEONATO_IN AND ISNULL(CXE.EXCLUIDO_BT,0) = 0
    
GO

GRANT EXECUTE ON USP_SELECIONARCAMPEONATOPORCODIGO TO PUBLIC

GO

IF ( SELECT COUNT(*)
     FROM   SYSOBJECTS
     WHERE  xtype = 'P'
            AND name = 'USP_ADICIONAREQUIPEAOCAMPEONATO'
   ) > 0 
    BEGIN
        DROP PROCEDURE USP_ADICIONAREQUIPEAOCAMPEONATO
    END

GO

CREATE PROCEDURE USP_ADICIONAREQUIPEAOCAMPEONATO
    (
      @CAMPEONATO_IN INT ,
      @EQUIPE_IN INT
    )
AS 
    INSERT  INTO dbo.CAMPEONATOXEQUIPE_T
            ( CAMPEONATO_IN ,
              EQUIPE_IN ,
              EXCLUIDO_BT
	        
            )
    VALUES  ( @CAMPEONATO_IN , -- CAMPEONATO_IN - int
              @EQUIPE_IN , -- EQUIPE_IN - int
              0  -- EXCLUIDO_BT - bit
	        
            )

GO

GRANT EXECUTE ON USP_ADICIONAREQUIPEAOCAMPEONATO TO PUBLIC

GO

IF ( SELECT COUNT(*)
     FROM   SYSOBJECTS
     WHERE  xtype = 'P'
            AND name = 'USP_REMOVEREQUIPEDOCAMPEONATO'
   ) > 0 
    BEGIN
        DROP PROCEDURE USP_REMOVEREQUIPEDOCAMPEONATO
    END

GO

CREATE PROCEDURE USP_REMOVEREQUIPEDOCAMPEONATO
    (
      @CAMPEONATO_IN INT ,
      @EQUIPE_IN INT
    )
AS 
    UPDATE  dbo.CAMPEONATOXEQUIPE_T
    SET     EXCLUIDO_BT = 1
    WHERE   CAMPEONATO_IN = @CAMPEONATO_IN
            AND EQUIPE_IN = @EQUIPE_IN
            
GO

GRANT EXECUTE ON USP_REMOVEREQUIPEDOCAMPEONATO TO PUBLIC



