IF ( SELECT COUNT(*)
     FROM   sysobjects
     WHERE  xtype = 'P'
            AND name = 'USP_SELECIONARCARTEGORIA'
   ) > 0 
    BEGIN
        DROP PROCEDURE USP_SELECIONARCARTEGORIA
    END

GO

CREATE PROCEDURE USP_SELECIONARCARTEGORIA
    (
      @Cartegoria_in INT = NULL
    )
AS 
    SELECT  DESCRICAO_VC ,
            ID_IN
    FROM    dbo.CARTEGORIA_T
    WHERE   ID_IN = ISNULL(@Cartegoria_in, ID_IN)
    
GO

GRANT EXECUTE ON USP_SELECIONARCARTEGORIA TO PUBLIC