CREATE TABLE CAMPEONATO_T
(
	ID_IN INT IDENTITY(1,1),
	NOME_VC VARCHAR(128) NOT NULL,
	DESCRICAO_VC VARCHAR(1024),
	EDICAO_IN INT,
	CARTEGORIA_IN INT,
	FACEBOOK_VC VARCHAR(128),
	INSTAGRAM_VC VARCHAR(128),
	DATAINICIO_DT DATETIME,
	DATAFINAL_DT DATETIME,
	ATIVO_BT BIT,
	USUARIOCADASTRO_VC VARCHAR(128),
	USUARIOULTIMAALTERACAO_VC VARCHAR(128),
	DATACADASTRO_DT DATETIME,
	DATAULTIMAALTERACAO_DT DATETIME,
	CONSTRAINT PK_CAMPEONATO_IN PRIMARY KEY(ID_IN)
)