CREATE TABLE EQUIPE_T
    (
      ID_IN INT IDENTITY(1, 1) ,
      NOME_VC VARCHAR(128) NOT NULL ,
      SIGLA_VC VARCHAR(128) NOT NULL ,
      RESPONSAVEL_VC VARCHAR(128) ,
      CONTATO1_VC VARCHAR(128) ,
      WHATSAPP1_BT BIT ,
      CONTATO2_VC VARCHAR(128) ,
      WHATSAP2_BT BIT ,
      EMAILCONTATO_VC VARCHAR(128) ,
      ENDERECOIMAGEM_VC VARBINARY(MAX) ,
      EXCLUIDO_BT BIT ,
      USUARIOCADASTRO_VC VARCHAR(128) ,
      USUARIOULTIMAALTERACAO_VC VARCHAR(128) ,
      DATACADASTRO_DT DATETIME ,
      DATAULTIMAALTERACAO_DT DATETIME CONSTRAINT PK_EQUIPE_IN PRIMARY KEY ( ID_IN )
    )