CREATE TABLE CAMPEONATOXEQUIPE_T
(
	ID_IN INT IDENTITY(1,1),
	CAMPEONATO_IN INT NOT NULL,
	EQUIPE_IN INT NOT NULL,
	CARTEGORIA_IN INT NOT NULL,
	CONSTRAINT PK_CAMPEONATOXEQUIPE_IN PRIMARY KEY(ID_IN),
	CONSTRAINT FK_CAMPEONATOXEQUIPE_T_CAMPEONATO_IN FOREIGN KEY(CAMPEONATO_IN) REFERENCES dbo.CAMPEONATO_T(ID_IN),
	CONSTRAINT FK_CAMPEONATOXEQUIPE_T_EQUIPE_IN FOREIGN KEY(EQUIPE_IN) REFERENCES dbo.EQUIPE_T(ID_IN),
	CONSTRAINT FK_CAMPEONATOXEQUIPE_T_CARTEGORIA_IN FOREIGN KEY(CARTEGORIA_IN) REFERENCES dbo.CARTEGORIA_T(ID_IN)
)	