CREATE TABLE EQUIPEXJOGADOR_T
(
	ID_IN INT IDENTITY(1,1),
	EQUIPE_IN INT NOT NULL,
	JOGADOR_IN INT NOT NULL,
	CARTEGORIA_IN INT NOT NULL,
	CONSTRAINT PK_EQUIPEXJOGADOR_IN PRIMARY KEY(ID_IN),
	CONSTRAINT FK_EQUIPEXJOGADOR_T_EQUIPE_IN FOREIGN KEY(EQUIPE_IN) REFERENCES dbo.EQUIPE_T(ID_IN),
	CONSTRAINT FK_EQUIPEXJOGADOR_T_JOGADOR_IN FOREIGN KEY(JOGADOR_IN) REFERENCES dbo.JOGADOR_T(ID_IN),
	CONSTRAINT FK_EQUIPEXJOGADOR_T_CARTEGORIA_IN FOREIGN KEY(CARTEGORIA_IN) REFERENCES dbo.CARTEGORIA_T(ID_IN)
)