ALTER TABLE dbo.CAMPEONATO_T ADD EXCLUIDO_BT BIT
ALTER TABLE dbo.EQUIPE_T ADD EXCLUIDO_BT BIT
ALTER TABLE dbo.JOGADOR_T ADD EXCLUIDO_BT BIT
ALTER TABLE dbo.CAMPEONATOXEQUIPE_T ADD EXCLUIDO_BT BIT
ALTER TABLE dbo.EQUIPEXJOGADOR_T ADD EXCLUIDO_BT BIT