IF ( SELECT COUNT(*)
     FROM   SYSOBJECTS
     WHERE  xtype = 'P'
            AND name = 'USP_ADICIONAREQUIPE'
   ) > 0 
    BEGIN
        DROP PROCEDURE USP_ADICIONAREQUIPE
    END

GO

CREATE PROCEDURE USP_ADICIONAREQUIPE
    (
      @NOME_VC VARCHAR(128) ,
      @SIGLA_VC VARCHAR(128) ,
      @RESPONSAVEL_VC VARCHAR(128) ,
      @CONTATO_VC1 VARCHAR(128) ,
      @WHATSAPP1_BT BIT ,
      @CONTATO2_VC VARCHAR(128) ,
      @WHATSAP2_BT BIT ,
      @EMAILCONTATO_VC VARCHAR(128) ,
      @ENDERECOIMAGEM_VC VARCHAR(1024) ,
      @CODIGO_IN INT OUTPUT
    )
AS 
    INSERT  INTO dbo.EQUIPE_T
            ( NOME_VC ,
              SIGLA_VC ,
              RESPONSAVEL_VC ,
              CONTATO1_VC ,
              WHATSAPP1_BT ,
              CONTATO2_VC ,
              WHATSAP2_BT ,
              EMAILCONTATO_VC ,
              USUARIOCADASTRO_VC ,
              USUARIOULTIMAALTERACAO_VC ,
              DATACADASTRO_DT ,
              DATAULTIMAALTERACAO_DT ,
              EXCLUIDO_BT ,
              ENDERECOIMAGEM_VC
	        
            )
    VALUES  ( @NOME_VC ,
              @SIGLA_VC ,
              @RESPONSAVEL_VC ,
              @CONTATO_VC1 ,
              @WHATSAPP1_BT ,
              @CONTATO2_VC ,
              @WHATSAP2_BT ,
              @EMAILCONTATO_VC ,
              CURRENT_USER , -- USUARIOCADASTRO_VC - varchar(128)
              CURRENT_USER , -- USUARIOULTIMAALTERACAO_VC - varchar(128)
              GETDATE() , -- DATACADASTRO_DT - datetime
              GETDATE() , -- DATAULTIMAALTERACAO_DT - datetime
              0 ,  -- EXCLUIDO_BT - bit
              @ENDERECOIMAGEM_VC
            )

    SET @CODIGO_IN = SCOPE_IDENTITY()

GO


GRANT EXECUTE ON USP_ADICIONAREQUIPE TO PUBLIC

GO

IF ( SELECT COUNT(*)
     FROM   SYSOBJECTS
     WHERE  xtype = 'P'
            AND name = 'USP_ALTERAREQUIPE'
   ) > 0 
    BEGIN
        DROP PROCEDURE USP_ALTERAREQUIPE
    END

GO

CREATE PROCEDURE USP_ALTERAREQUIPE
    (
	  @EQUIPE_IN INT,	
      @NOME_VC VARCHAR(128) ,
      @SIGLA_VC VARCHAR(128) ,
      @RESPONSAVEL_VC VARCHAR(128) ,
      @CONTATO_VC1 VARCHAR(128) ,
      @WHATSAPP1_BT BIT ,
      @CONTATO2_VC VARCHAR(128) ,
      @WHATSAP2_BT BIT ,
      @EMAILCONTATO_VC VARCHAR(128) ,
      @ENDERECOIMAGEM_VC VARCHAR(1024)
    )
AS 
    UPDATE  dbo.EQUIPE_T
    SET     NOME_VC = @NOME_VC ,
            SIGLA_VC = @SIGLA_VC ,
            RESPONSAVEL_VC = @RESPONSAVEL_VC ,
            CONTATO1_VC = @CONTATO_VC1 ,
            WHATSAPP1_BT = @WHATSAPP1_BT ,
            CONTATO2_VC = @CONTATO2_VC ,
            WHATSAP2_BT = @WHATSAP2_BT ,
            EMAILCONTATO_VC = @EMAILCONTATO_VC ,
            ENDERECOIMAGEM_VC = @ENDERECOIMAGEM_VC,
            USUARIOULTIMAALTERACAO_VC = SYSTEM_USER ,
            DATAULTIMAALTERACAO_DT = GETDATE()
    WHERE	ID_IN = @EQUIPE_IN
            
            
    
GO

GRANT EXECUTE ON USP_ALTERAREQUIPE TO PUBLIC

GO

IF ( SELECT COUNT(*)
     FROM   SYSOBJECTS
     WHERE  xtype = 'P'
            AND name = 'USP_APAGAREQUIPE'
   ) > 0 
    BEGIN
        DROP PROCEDURE USP_APAGAREQUIPE
    END

GO

CREATE PROCEDURE USP_APAGAREQUIPE ( @EQUIPE_IN INT )
AS 
    UPDATE  dbo.EQUIPE_T
    SET     EXCLUIDO_BT = 1
    WHERE   ID_IN = @EQUIPE_IN
    UPDATE  dbo.EQUIPEXJOGADOR_T
    SET     EXCLUIDO_BT = 1
    WHERE   EQUIPE_IN = @EQUIPE_IN
GO

GRANT EXECUTE ON USP_APAGAREQUIPE TO PUBLIC

GO

IF ( SELECT COUNT(*)
     FROM   SYSOBJECTS
     WHERE  xtype = 'P'
            AND name = 'USP_SELECIONAREQUIPEPORCODIGO'
   ) > 0 
    BEGIN
        DROP PROCEDURE USP_SELECIONAREQUIPEPORCODIGO
    END

GO

CREATE PROCEDURE dbo.USP_SELECIONAREQUIPEPORCODIGO ( @EQUIPE_IN INT = NULL )
AS --TRAGO AS INFORMAÇÕES DA EQUIOE 
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	
    SELECT  ID_IN,
			NOME_VC ,
            SIGLA_VC ,
            RESPONSAVEL_VC ,
            CONTATO1_VC ,
            WHATSAPP1_BT ,
            CONTATO2_VC ,
            WHATSAP2_BT ,
            EMAILCONTATO_VC ,
            USUARIOCADASTRO_VC ,
            USUARIOULTIMAALTERACAO_VC ,
            DATACADASTRO_DT ,
            DATAULTIMAALTERACAO_DT ,
            ENDERECOIMAGEM_VC ,
            EXCLUIDO_BT
    FROM    dbo.EQUIPE_T
    WHERE   ID_IN = ISNULL(@EQUIPE_IN,ID_IN)
--TRAGO AS INFORMAÇÕES DO JOGADOR
    SELECT  JOG.ID_JOGADOR_IN ,
            JOG.APELIDO_VC ,
            JOG.CARTEGORIA_IN ,
            CAT.DESCRICAO_VC ,
            JOG.EQUIPE_IN ,
            JOG.NOMEATLETA_VC ,
            JOG.APELIDO_VC VA ,
            JOG.DATANASCIMENTO_DT ,
            JOG.LOCALNASCIMENTO_VC ,
            JOG.CERTIDAONASCIMENTO_VC ,
            JOG.IDENTIDADE_VC ,
            JOG.ORGAOIDENTIDADE_VC ,
            JOG.NOMEPAI_VC ,
            JOG.STRNOMEMAE_VC ,
            JOG.ESTADO_IN ,
            JOG.CIDADE_VC ,
            JOG.BAIRRO_VC ,
            JOG.ENDERECO_VC ,
            JOG.EMAIL_VC ,
            JOG.FACEBOOK_VC ,
            JOG.ESCOLA_VC ,
            JOG.CIDADEESCOLA_VC ,
            JOG.BAIRROESCOLA_VC ,
            JOG.ENDERECOESCOLA_VC ,
            JOG.REDESOCIALESCOLA_VC ,
            JOG.ENDERECOIMAGEM_VC ,
            JOG.USUARIOCADASTRO_VC ,
            JOG.USUARIOULTIMAALTERACAO_VC ,
            JOG.DATACADASTRO_DT ,
            JOG.DATAULTIMAALTERACAO_DT ,
            EQU.NOME_VC AS Nome_Equipe
    FROM    dbo.JOGADOR_T JOG
            INNER JOIN dbo.EQUIPE_T EQU ON JOG.EQUIPE_IN = EQU.ID_IN
            INNER JOIN dbo.CARTEGORIA_T CAT ON JOG.CARTEGORIA_IN = CAT.ID_IN
    WHERE   JOG.EQUIPE_IN = ISNULL(@EQUIPE_IN,EQUIPE_IN)
            AND NOT ISNULL(JOG.EXCLUIDO_BT, 0) = 1
    
GO

GRANT EXECUTE ON USP_SELECIONAREQUIPEPORCODIGO TO PUBLIC
