IF (SELECT COUNT(*) FROM sysobjects WHERE xtype = 'P' AND name = 'USP_ADICIONARALTERARFOTOJOGADOR') > 0
BEGIN
	DROP PROCEDURE USP_ADICIONARALTERARFOTOJOGADOR
END

GO

CREATE PROCEDURE USP_ADICIONARALTERARFOTOJOGADOR
    (
      @Jogador_IN INT ,
      @Caminhofoto_VC VARCHAR(1024)
    )
AS 
    UPDATE  dbo.JOGADOR_T
    SET     ENDERECOIMAGEM_VC = @Caminhofoto_VC
    WHERE   ID_JOGADOR_IN = @Jogador_IN
	
GO

GRANT EXECUTE ON USP_ADICIONARALTERARFOTOJOGADOR TO PUBLIC