CREATE TABLE PARAMETROS_T
    (
      ID_IN INT IDENTITY(1, 1) ,
      CODIGO_IN INT ,
      DESCRICAO_VC VARCHAR(1024) ,
      VALOR_IN INT
    )

GO

CREATE PROCEDURE USP_RETORNARPARAMETROPORCODIGO ( @Codigo_IN INT )
AS 
    SELECT  VALOR_IN
    FROM    PARAMETROS_T
    WHERE   CODIGO_IN = @Codigo_IN
    
GO

GRANT EXECUTE ON USP_RETORNARPARAMETROPORCODIGO TO PUBLIC