CREATE PROCEDURE dbo.usp_AlterarEquipe
    (
      @EQUIPE_IN INT ,
      @NOME_VC VARCHAR(128) ,
      @SIGLA_VC VARCHAR(128) ,
      @RESPONSAVEL_VC VARCHAR(128) ,
      @CONTATO_VC1 VARCHAR(128) ,
      @WHATSAPP1_BT BIT ,
      @CONTATO2_VC VARCHAR(128) ,
      @WHATSAP2_BT BIT ,
      @EMAILCONTATO_VC VARCHAR(128) ,
      @ENDERECOIMAGEM_VC VARBINARY(MAX) = NULL
    )
AS 
    UPDATE  dbo.EQUIPE_T
    SET     NOME_VC = @NOME_VC ,
            SIGLA_VC = @SIGLA_VC ,
            RESPONSAVEL_VC = @RESPONSAVEL_VC ,
            CONTATO1_VC = @CONTATO_VC1 ,
            WHATSAPP1_BT = @WHATSAPP1_BT ,
            CONTATO2_VC = @CONTATO2_VC ,
            WHATSAP2_BT = @WHATSAP2_BT ,
            EMAILCONTATO_VC = @EMAILCONTATO_VC ,
            ENDERECOIMAGEM_VC = @ENDERECOIMAGEM_VC ,
            USUARIOULTIMAALTERACAO_VC = SYSTEM_USER ,
            DATAULTIMAALTERACAO_DT = GETDATE()
    WHERE   ID_IN = @EQUIPE_IN
            
            
    

GO


