CREATE PROCEDURE dbo.USP_SELECIONAREQUIPEPORCODIGO ( @EQUIPE_IN INT = NULL )
AS --TRAGO AS INFORMAÇÕES DA EQUIOE 
    SET NOCOUNT ON
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	
    SELECT  ID_IN ,
            NOME_VC ,
            SIGLA_VC ,
            RESPONSAVEL_VC ,
            CONTATO1_VC ,
            WHATSAPP1_BT ,
            CONTATO2_VC ,
            WHATSAP2_BT ,
            EMAILCONTATO_VC ,
            USUARIOCADASTRO_VC ,
            USUARIOULTIMAALTERACAO_VC ,
            DATACADASTRO_DT ,
            DATAULTIMAALTERACAO_DT ,
            ENDERECOIMAGEM_VC ,
            EXCLUIDO_BT
    FROM    dbo.EQUIPE_T
    WHERE   ID_IN = ISNULL(@EQUIPE_IN, ID_IN)
--TRAGO AS INFORMAÇÕES DO JOGADOR
    SELECT  JOG.ID_JOGADOR_IN ,
            JOG.APELIDO_VC ,
            JOG.CARTEGORIA_IN ,
            CAT.DESCRICAO_VC ,
            JOG.EQUIPE_IN ,
            JOG.NOMEATLETA_VC ,
            JOG.APELIDO_VC VA ,
            JOG.DATANASCIMENTO_DT ,
            JOG.LOCALNASCIMENTO_VC ,
            JOG.CERTIDAONASCIMENTO_VC ,
            JOG.IDENTIDADE_VC ,
            JOG.ORGAOIDENTIDADE_VC ,
            JOG.NOMEPAI_VC ,
            JOG.STRNOMEMAE_VC ,
            JOG.ESTADO_IN ,
            JOG.CIDADE_VC ,
            JOG.BAIRRO_VC ,
            JOG.ENDERECO_VC ,
            JOG.EMAIL_VC ,
            JOG.FACEBOOK_VC ,
            JOG.ESCOLA_VC ,
            JOG.CIDADEESCOLA_VC ,
            JOG.BAIRROESCOLA_VC ,
            JOG.ENDERECOESCOLA_VC ,
            JOG.REDESOCIALESCOLA_VC ,
            JOG.ENDERECOIMAGEM_VC ,
            JOG.USUARIOCADASTRO_VC ,
            JOG.USUARIOULTIMAALTERACAO_VC ,
            JOG.DATACADASTRO_DT ,
            JOG.DATAULTIMAALTERACAO_DT ,
            EQU.NOME_VC AS Nome_Equipe,
            JOG.NUMEROCAMISA_IN,
            JOG.SEXO_IN
    FROM    dbo.JOGADOR_T JOG
            INNER JOIN dbo.EQUIPE_T EQU ON JOG.EQUIPE_IN = EQU.ID_IN
            INNER JOIN dbo.CARTEGORIA_T CAT ON JOG.CARTEGORIA_IN = CAT.ID_IN
    WHERE   JOG.EQUIPE_IN = ISNULL(@EQUIPE_IN, EQUIPE_IN)
            AND NOT ISNULL(JOG.EXCLUIDO_BT, 0) = 1
    
GO
